import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { WalletContextProvider } from "@/context/wallet";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Votting",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <WalletContextProvider>
        <body
          className={`${inter.className} text-[#EAECEF] bg-[#202328]`}
        >
          {children}
        </body>
      </WalletContextProvider>
    </html>
  );
}
